<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>CollegeAccessSystem</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CollegeAccessSystem.Adapters.Inbound.Api\CollegeAccessSystem.Adapters.Inbound.Api.csproj" />
      <ProjectReference Include="..\CollegeAccessSystem.Adapters.Outbound.Persistence\CollegeAccessSystem.Adapters.Outbound.Persistence.csproj" />
      <ProjectReference Include="..\CollegeAccessSystem.Core.Application\CollegeAccessSystem.Core.Application.csproj" />
    </ItemGroup>

</Project>
